### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by thelastsummer** [contra/spotcrime#12]
when I tried this api, I got such issue
{
    "errors": [
        "Invalid API Key"
    ]
}

how can I fix this issue?

**Comment by contra** [comment]
Just checked the keys, they seem to be valid.

**Comment by thelastsummer** [comment]
yeah
it was my fault, I forgot adding key parameter
Thank you

**Comment by thelastsummer** [comment]
I got such error again
seems it is really key problem

    NSString *key = @"privatekeyforspotcrimepublicusers-commercialuse-877.410.1607";
        NSURL *url2 = [NSURL URLWithString:[NSString 
    stringWithFormat:@"http://api.spotcrime.com/crimes.json?
    lat=%f&lon=%f&radius=0.01&key=%@&callback=", newLocation.coordinate.latitude, 
    newLocation.coordinate.longitude,key]];

can you check again?

**Comment by contra** [comment]
Can you paste the error?

Your code doesn't use this module, btw - can't really provide support for your objective-c app. I don't have any affiliation with spotcrime, I just made a JS module to access it.

**Comment by thelastsummer** [comment]
Please ignore objective c code
I got this error

{
"errors": [
"Invalid API Key"
]
}

**Comment by contra** [comment]
2.0.0 should work
