### ISSUE TITLE
Webpack 3 dependencies

### ISSUE THREAD

**Issue by not-a-designer** [contra/spotcrime#13]
I  am getting an error when trying to add this package via NPM to my angular app

in doing some research, it looks like some of Spotcrime's dependencies are built in to webpack now (crypto, net, tls, etc). is there hope for an update?

# Error
>ERROR in ./node_modules/aws-sign2/index.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\aws-sign2'
[ng] ERROR in ./node_modules/aws4/aws4.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\aws4'
[ng] ERROR in ./node_modules/ecc-jsbn/index.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\ecc-jsbn'
[ng] ERROR in ./node_modules/http-signature/lib/signer.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\http-signature\lib'
[ng] ERROR in ./node_modules/http-signature/lib/verify.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\http-signature\lib'
[ng] ERROR in ./node_modules/oauth-sign/index.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\oauth-sign'
[ng] ERROR in ./node_modules/request/lib/hawk.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\request\lib'
[ng] ERROR in ./node_modules/request/lib/oauth.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\request\lib'
[ng] ERROR in ./node_modules/request/lib/helpers.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\request\lib'
[ng] ERROR in ./node_modules/sshpk/lib/key.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/dhe.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/utils.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/fingerprint.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/signature.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/private-key.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/certificate.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/identity.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib'
[ng] ERROR in ./node_modules/sshpk/lib/formats/pem.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib\formats'
[ng] ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib\formats'
[ng] ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
[ng] Module not found: Error: Can't resolve 'crypto' in 'Z:\ionic\app\node_modules\sshpk\lib\formats'
[ng] ERROR in ./node_modules/request/lib/har.js
[ng] Module not found: Error: Can't resolve 'fs' in 'Z:\ionic\app\node_modules\isstream'
[ng] ERROR in ./node_modules/request/request.js
[ng] Module not found: Error: Can't resolve 'zlib' in 'Z:\ionic\app\node_modules\request'
[ng] i ｢wdm｣: Failed to compile.

# package.json
>"dependencies": {
    "@angular/common": "~7.0.2",
    "@angular/core": "~7.0.2",
    "@angular/forms": "~7.0.2",
    "@angular/http": "~7.0.2",
    "@angular/platform-browser": "~7.0.2",
    "@angular/platform-browser-dynamic": "~7.0.2",
    "@angular/router": "~7.0.2",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-beta.15",
    "core-js": "^2.5.7",
    "rxjs": "6.3.3",
    "spotcrime": "^1.0.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.10.4",
    "@angular-devkit/build-angular": "~0.10.4",
    "@angular-devkit/core": "~7.0.4",
    "@angular-devkit/schematics": "~7.0.4",
    "@angular/cli": "~7.0.4",
    "@angular/compiler": "~7.0.2",
    "@angular/compiler-cli": "~7.0.2",
    "@angular/language-service": "~7.0.2",
    "@ionic/angular-toolkit": "^1.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  },

**Comment by contra** [comment]
Pushed a 2.0.0 that should solve this
