### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by abrowne2** [contra/spotcrime#9]
I had created a PR for this, but there is really no reason for a PR.

You can analyze spotcrime.com when a request is made to its API, and the key is revealed:

http://api.spotcrime.com/crimes.json?lat=####&lon=###&radius=0.02&key=.

Spotcrime's API can be accessed by the key, "."

**Comment by contra** [comment]
Is the current key in the repo not working?

**Comment by abrowne2** [comment]
The key in the repo does not work, at least when I attempt to make a request to the api. The period ".", when used for a key, does work.
